version: '3.8'

services:
  database:
    image: postgres:15
    container_name: rental-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rental_service
    ports:
      - "5542:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
